### ISSUE TITLE
Mybatis数据库连接异常

### ISSUE THREAD

**Issue by ChinaLHR** [SzPluto/elemeHongbao#1]
"nested exception is org.apache.ibatis.exceptions.PersistenceException: ↵### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.↵### The error may exist in class path resource [mapper/AltMapper.xml]↵### The error may involve com.eleme.dao.AltDao.findMaxId↵### The error occurred while executing a query↵### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms."

![image](https://user-images.githubusercontent.com/19829495/39342224-930dd452-4a09-11e8-95ca-7a34b45e8ab6.png)

**Comment by SzPluto** [comment]
这个应该是昨天发生的mysql内存占用过高自动killed了
已经解决不过还需要继续观察
